version: "3"
services:
  gh22-go:
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - app.env
    volumes:
      - ../:/app
    restart: unless-stopped

  postgres-gh22-go:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - db.env
    restart: unless-stopped
    volumes:
      - postgres-gh22-go:/var/lib/postgresql/data
volumes:
  postgres-gh22-go: